name: Build Macrium Converter

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code with Submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -S src -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build Code
      run: cmake --build build --config Release --parallel

    - name: Upload Compiled Executable
      uses: actions/upload-artifact@v4
      with:
        name: img_to_vhdx-executable
        path: |
          build/IMG_TO_VHDX/Release/img_to_vhdx.exe
          build/Release/img_to_vhdx.exe
          build/src/Release/img_to_vhdx.exe
